services:
  web:
    image: nginx
    volumes:
      - ./public:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    environment:
      - NGINX_PORT=80
    ports:
      - 8082:80
  node:
    restart: on-failure
    build: ./app
    init: true
    hostname: node
    ports:
      - '127.0.0.1:8083:8085'
  redis:
    image: 'docker.io/library/redis'
    restart: always
    ports:
      - '127.0.0.1:6380:6379'
