spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/media
    driver-class-name: org.postgresql.Driver
    username: ultrafox
    password: EekAwtQdehfLZC2i8PaTnOYjVoSzoOVl
  redis:
    host: localhost
    port: 6379
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect:
          org.hibernate.dialect.PostgreSQLDialect
  server:
    port:
      8080
  config:
    import: 'file:config.yml'
token:
  signing:
    key: 9191b63f5fde8bd2a44f1aa3cf776bd04a9bb98dd60e5f9d680bb911fbb03301